import axios from "axios" ///amader ReactJs project ar moddhe amra axios package take install korar pore akhane import kore diyechi...and ai axios ar maddhome amra API ar moddhe theke data fetch korte pari...ta chara amra chaile ReactJs ar builtin useEffect() hook use kore ooo API theke data fetch korte pari....

import { GET_TODOS_REQUEST } from "../constants/TodosConstant" /////akhane amader constants guloke import kore niye ashechi mane amader action ar type ar nam gulo jei file ar moddhe store kore rekhechi oi file ar moddhe theke oi variable guloke niye ashechi and amader oi file ar moddhe theke amader variable gulo shudhu export korechi tai akhane import korar somoy amader oi variable guloke { } object ar moddhe rekhechi jodi amra oi file ar moddhe theke amader amader ai variable gulo export  default kortam tahole akhane import korar somoy sorasori amader oi variable ar nam ta likhe dite partam tokhon amader r oi variable nam take { } object ar moddhe rakhte hoto na 
import { GET_TODOS_SUCCESS } from "../constants/TodosConstant"
import { GET_TODOS_FAILD } from "../constants/TodosConstant"

const getAllTodosAction = () => async (dispatch) => { /////jehetu amder action take akta function ar moddhe rekhe return korchi tai ai getAllTodosAction function take bola hobe Action Creator Function.....amra jani amader action { } object ar moddhe lekha hoy and action ar moddhe 2ta jinish thake 'type' ai type ar moddhe amader action ar type  ta bole dei amader action type ta ki hobe and ai action  type ta amra akta variable ar moddhe define kore then oi variable ar nam ta akhene likhe dite hobe karon amader ai nam ta aabar amader Reduser ar moddhe likhe te hobe tai jeno amader speling mistek na hoy tar jonno amra amder action ar type ar nam ta akta variable ar moddhe store kore rakhbo src/services/constants and oi variable take use korbo and action ar moddhe 'payload' ooo thake and ai payload ar maddhome amra action ar moddhe theke Reducer ar moddhe data pass korte pari...and akhane amra akta asyncronous action create korchi karon amra store ar moddhe redux-thunk nam aa akta middleware use korechi jei middleware ar maddhome amra asyncronous action create korte pari and oi action ar moddhe amra API theke data fetch korte pari asyncronous vabe
    dispatch({ type: GET_TODOS_REQUEST })  ////akhane amra akta action dispatch korechi and ai action ar type oonujayi amader ai action ta Reducer ar moddhe jabe and Reducer ar moddhe action ar type oonujayi logic handel kore amader state take update kore Store ar moddhe pass kore debe and amder Store ar moddhe theke oi updated state ar value oonujayi amader View ta Update hoye jabe and amra dekhte parbo

    try {  ///jodi amader try bock ar moddhe jei code ta ache ai code ar moddhe kono error ashe tahole oi error take amadre niche catch korbe
        const res = await axios.get("https://jsonplaceholder.typicode.com/todos") ////opore jehetu ami async likhechi tai akhane await likhechi mane jotokhon porjonto na amader ai line ar kaj hoye jabe mane API theke axios ar maddhome data fetch hoye jotokkhon porjonto na amader  res variable ar moddhe oi data ta set hoye jabe totokhon porjonto amader nicher line aaa jabe na ..
        dispatch({ type: GET_TODOS_SUCCESS, payload: res.data }) ///akhane amader r akta action dispatch korechi and akhane action ar moddhe type diye bole diyechi ai action ar type ta ki and payload ar moddhe ami res variable ar moddhe jei data ta ache oi data take pass kore diyechi payload: res.data likhe and ai payload ar moddhe jei data ta pass korechi amader ai action ar moddhe theke ai payload ar data ta amader Reducer ar moddhe chole jabe karon amra jani jokhon ee amader kono action dispatch hoy tokhon eee amader oi action ta action type and payload ar moddhe data niye jai amader Reducer ar moddhe and amader Reducer oi action ar type oonujayi logic guloke handel kore amader state ar value guloke update kore Store ar moddhe pass kore dei and store ar moddhe theke amader updated state ar value ta diye amder View take update kore dei Store
    } catch (error) { /////error take akhane catch korbe 
        dispatch({type: GET_TODOS_FAILD , payload: error.message}) ///akhan theke akta action dispatch hobe 
    }
}

export default getAllTodosAction