import { configureStore } from "@reduxjs/toolkit" ////amader ai ReactJs project ar moddhe amra jei Redux toolkit package ta install korechi oi Redux toolkit ar moddhe theke amra configureStore method take import korchi

import BooksReduser from "../freatures/books/BooksSlice" ////akhane amader BooksSlice.jsx file ar moddhe theke ami amader booksSlice take import korechi and jehetu amader BooksSlice.jsx file ar moddhe theke ami amader booksSlice take import korechi and jehetu amader booksSlice ke export default korechi tai akhane ami oitake je kono nam aaa  import korte parbo tai ami akhane BooksReduser ai nam aa import korechi

const Store = configureStore({  /////ai configureStore() method ar moddhe amra amader reducer guloke akta object ar moddhe rekhe dite pari .....jokhon amra ai store ar kaj ta amader shudhu ReactJs and Redux use kore kortam tokhon amra Redux ar moddhe theke createStore() method take call kore tar moddhe amader Reducer ar nam ta likhe ditam and amra chaile tar moddhe middleware ooo likhte partam applyMiddleware() ar moddhe amder middleware ar nam ta likhe ditam kintu Redux toolkit ar moddhe amra configureStore ai method ar moddhe ai kaj gulo kori
    reducer: { /////amader sob reducer guloke amra ai reducer object ar moddhe rekhe dite pari
        Allbooks: BooksReduser  ////akhane amader BooksReduser ke books key ar moddhe store kore diyechi ...and amra chaile amader r ooo reducer ke amra ai object { } ar moddhe key pair aaa set kore dite pari
    }
})

export default Store /////akhane amader Store take export default kore diyechi tai jekono page ar moddhe theke amader ai Store take import kora jabe sora sori nam likhe { } object ar moddhe nam lekhar kono proyojon nei karon ami akhan theke export default korechi tai and ai Store ar moddhe amader Updated state ar value ta ashbe Reduser theke and oi updated state ar value ta amader ai store ar moddhe theke view ar moddhe update korar jonno amader ai Store take main.jsx ar moddhe theke golobally set kore dite hobe jar fole amader amader main.jsx ar joto child ache oi child gulo amader ai Store ar value take access korte parbe and view take update kore dite parbe ai Store ar moddhe jei updated state ta ashbe oi state ar value oonujayi